import PDFDocument from "pdfkit";

const COLORS = {
  primary: "#2563eb",
  dark: "#0f172a",
  gray: "#475569",
  light: "#94a3b8",
  green: "#059669",
  red: "#dc2626",
  amber: "#d97706",
};

const scoreColor = (score) => {
  if (score >= 70) return COLORS.green;
  if (score >= 40) return COLORS.amber;
  return COLORS.red;
};

const drawHeader = (doc, title, subtitle) => {
  doc
    .fillColor(COLORS.primary)
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("AI Interview Platform", { align: "left" });

  doc
    .fillColor(COLORS.gray)
    .fontSize(10)
    .font("Helvetica")
    .text("Industry-Ready Interview Preparation Report", { align: "left" });

  doc.moveDown(1.2);

  doc
    .fillColor(COLORS.dark)
    .fontSize(18)
    .font("Helvetica-Bold")
    .text(title);

  if (subtitle) {
    doc
      .fillColor(COLORS.gray)
      .fontSize(11)
      .font("Helvetica")
      .text(subtitle);
  }

  doc
    .moveDown(0.5)
    .strokeColor("#e2e8f0")
    .lineWidth(1)
    .moveTo(doc.x, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();

  doc.moveDown(1);
};

const drawScoreRow = (doc, label, score) => {
  const startX = doc.x;
  const y = doc.y;

  doc.fillColor(COLORS.gray).fontSize(11).font("Helvetica").text(label, startX, y, { continued: false });

  doc
    .fillColor(scoreColor(score))
    .fontSize(13)
    .font("Helvetica-Bold")
    .text(`${score}%`, startX, y, { align: "right" });

  doc.moveDown(0.3);

  const barWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const filledWidth = Math.max(0, Math.min(100, score)) / 100 * barWidth;

  doc
    .rect(doc.x, doc.y, barWidth, 6)
    .fill("#e2e8f0");

  doc
    .rect(doc.x, doc.y, filledWidth, 6)
    .fill(scoreColor(score));

  doc.moveDown(1);
};

const drawSectionTitle = (doc, text) => {
  doc.moveDown(0.5);
  doc
    .fillColor(COLORS.dark)
    .fontSize(13)
    .font("Helvetica-Bold")
    .text(text);
  doc.moveDown(0.3);
};

/**
 * Generate a PDF report for a STATIC interview (models/Interview.js doc).
 * Returns a PDFDocument stream - pipe it to the response.
 */
export const generateInterviewReportPDF = (interview, userName) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  drawHeader(
    doc,
    "Interview Performance Report",
    `${userName || "Candidate"} • ${interview.role || "N/A"} at ${interview.company || "N/A"}`
  );

  doc.fillColor(COLORS.gray).fontSize(10).text(
    `Experience: ${interview.experience || "N/A"}   |   Difficulty: ${interview.difficulty || "N/A"}   |   Date: ${new Date(interview.createdAt).toLocaleDateString()}`
  );

  drawSectionTitle(doc, "Overall Scores");

  drawScoreRow(doc, "Overall Score", interview.overallScore || 0);
  drawScoreRow(doc, "Technical", interview.technical || 0);
  drawScoreRow(doc, "Communication", interview.communication || 0);
  drawScoreRow(doc, "Confidence", interview.confidence || 0);
  drawScoreRow(doc, "Grammar", interview.grammar || 0);

  if (interview.feedback) {
    drawSectionTitle(doc, "Overall Feedback");
    doc.fillColor(COLORS.gray).fontSize(11).font("Helvetica").text(interview.feedback);
  }

  drawSectionTitle(doc, "Question-by-Question Breakdown");

  (interview.answers || []).forEach((qa, i) => {
    doc
      .fillColor(COLORS.dark)
      .fontSize(11)
      .font("Helvetica-Bold")
      .text(`Q${i + 1}. ${qa.question || ""}`);

    doc
      .fillColor(COLORS.gray)
      .fontSize(10)
      .font("Helvetica")
      .text(`Answer: ${qa.answer || "(No answer given)"}`);

    doc.moveDown(0.8);

    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
  });

  doc
    .moveDown(1)
    .fillColor(COLORS.light)
    .fontSize(8)
    .text("Generated by AI Interview Platform", { align: "center" });

  return doc;
};

/**
 * Generate a PDF report for an ADAPTIVE interview session
 * (models/InterviewSession.js doc).
 */
export const generateAdaptiveReportPDF = (session, userName) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  drawHeader(
    doc,
    "Adaptive AI Interview Report",
    `${userName || "Candidate"} • ${session.role || "N/A"} at ${session.company || "N/A"}`
  );

  doc.fillColor(COLORS.gray).fontSize(10).text(
    `Experience: ${session.experience || "N/A"}   |   Final Difficulty: ${session.difficulty || "N/A"}   |   Date: ${new Date(session.createdAt).toLocaleDateString()}`
  );

  drawSectionTitle(doc, "Overall Score");
  drawScoreRow(doc, "Overall Score", session.overallScore || 0);

  drawSectionTitle(doc, "Adaptive Question Flow");

  (session.answers || []).forEach((qa, i) => {
    doc
      .fillColor(COLORS.dark)
      .fontSize(11)
      .font("Helvetica-Bold")
      .text(`Q${i + 1}. [${qa.difficulty || "Medium"}] ${qa.question || ""}`);

    doc
      .fillColor(COLORS.gray)
      .fontSize(10)
      .font("Helvetica")
      .text(`Answer: ${qa.answer || "(No answer given)"}`);

    doc
      .fillColor(scoreColor(qa.score || 0))
      .fontSize(10)
      .font("Helvetica-Bold")
      .text(`Score: ${qa.score || 0}/100`);

    if (qa.aiFeedback) {
      doc
        .fillColor(COLORS.primary)
        .fontSize(10)
        .font("Helvetica-Oblique")
        .text(`Feedback: ${qa.aiFeedback}`);
    }

    doc.moveDown(0.8);

    if (doc.y > doc.page.height - 100) {
      doc.addPage();
    }
  });

  doc
    .moveDown(1)
    .fillColor(COLORS.light)
    .fontSize(8)
    .text("Generated by AI Interview Platform", { align: "center" });

  return doc;
};
