import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadInterviewReport = (
  evaluation,
  interviewData
) => {

  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.text("AI Interview Report", 20, 20);

  doc.setFontSize(12);

  doc.text(
    `Company : ${interviewData.company}`,
    20,
    35
  );

  doc.text(
    `Role : ${interviewData.role}`,
    20,
    43
  );

  doc.text(
    `Experience : ${interviewData.experience}`,
    20,
    51
  );

  doc.text(
    `Difficulty : ${interviewData.difficulty}`,
    20,
    59
  );

  autoTable(doc, {

    startY: 70,

    head: [["Category", "Score"]],

    body: [

      ["Overall", evaluation.overallScore],

      ["Technical", evaluation.technical],

      ["Communication", evaluation.communication],

      ["Confidence", evaluation.confidence],

      ["Grammar", evaluation.grammar],

    ],

  });

  let y = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(16);
  doc.text("AI Feedback", 20, y);

  y += 10;

  doc.setFontSize(11);

  doc.text(
    evaluation.feedback,
    20,
    y,
    {
      maxWidth: 170,
    }
  );

  y += 30;

  doc.setFontSize(15);

  doc.text("Strengths", 20, y);

  y += 8;

  evaluation.strengths.forEach((item) => {

    doc.text(`• ${item}`, 25, y);

    y += 7;

  });

  y += 5;

  doc.text("Weaknesses", 20, y);

  y += 8;

  evaluation.weaknesses.forEach((item) => {

    doc.text(`• ${item}`, 25, y);

    y += 7;

  });

  y += 5;

  doc.text("Improvements", 20, y);

  y += 8;

  evaluation.improvements.forEach((item) => {

    doc.text(`• ${item}`, 25, y);

    y += 7;

  });

  y += 15;

  doc.setFontSize(16);

  doc.text(
    `Recommendation : ${evaluation.recommendation}`,
    20,
    y
  );

  y += 20;

  doc.setFontSize(10);

  doc.text(
    "Generated by AI Interview Platform",
    20,
    y
  );

  doc.save("AI_Interview_Report.pdf");

};